In [4]:
import numpy as np

In [5]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.randn(2)

array([ 0.95104256, -1.60776381])

In [20]:
np.random.randn(5,5)

array([[ 1.34241364e+00,  8.06653701e-01,  4.52897696e-01,
         5.40255828e-05, -1.06429762e+00],
       [ 7.51475717e-01, -2.32866283e-01, -2.41836998e-01,
         2.33404560e+00, -5.37977756e-01],
       [ 5.67372533e-01, -7.13504877e-01, -2.59797767e-01,
         7.78653621e-01, -1.66598062e+00],
       [-8.11068321e-01, -3.66698666e-01, -9.32323217e-01,
        -1.04408686e+00,  4.70218665e-02],
       [-1.18409934e+00, -1.67542850e-01, -9.32739955e-01,
        -1.48422998e-01, -1.68382123e+00]])

In [21]:
np.random.randint(1,50)

11

In [29]:
np.random.randint(1,6,10)

array([2, 2, 1, 1, 5, 3, 2, 2, 1, 5])

In [31]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr=np.random.randint(0,50,10)
ranarr

array([ 4, 19, 18, 24, 15, 29, 27, 20,  7, 44])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.max()

24

In [41]:
arr.min()

0

In [38]:
arr.argmin()

0

In [40]:
arr.argmax()

24

In [42]:
ranarr

array([ 4, 19, 18, 24, 15, 29, 27, 20,  7, 44])

In [43]:
ranarr.max()

44

In [45]:
ranarr.min()

4

In [ ]:
ranarr

In [46]:
arr.shape

(25,)

In [47]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
arr.reshape(25,1).shape

(25, 1)

In [50]:
arr.dtype

dtype('int32')

In [83]:
arr=np.arange(0,11)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[8]

8

In [54]:
arr[1:5]

array([1, 2, 3, 4])

In [55]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [56]:
arr[0:5]*5

array([ 0,  5, 10, 15, 20])

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[0:5]=100

In [59]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[:]=1000

In [65]:
arr

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr[1:5].copy()

array([1, 2, 3, 4])

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[:]=333.copy()

SyntaxError: invalid syntax (<ipython-input-74-d69dd7861f30>, line 1)

In [73]:
arr

array([333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333])

In [78]:
slice_of_arr = arr[0:6]

In [79]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [80]:
slice_of_arr[:]=99

In [81]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [82]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
slice_of_arr = arr[0:6].copy()

In [87]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [88]:
slice_of_arr[:]=99

In [89]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [90]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr_2d=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [100]:
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [101]:
arr_2d[2]

[7, 8, 9]

In [102]:
arr_2d[0][2]

3

In [104]:
arr_2d[1:2]

[[4, 5, 6]]

In [108]:
arr2=np.arange(1,11)

In [112]:
arr2[arr2>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr2[arr2==2]

array([2])

In [114]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr2*arr2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [116]:
np.sqrt(arr2)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [117]:
np.exp(arr2)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [118]:
np.max(arr2)

10

In [119]:
np.log(arr2)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])